apiVersion: v1
kind: Service
metadata:
    name: course-api-service
spec:
    selector:
        app: course-api
    #type: LoadBalancer
    ports:
    - port: 3030
      targetPort: 3030
      protocol: TCP