kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gcs-reader-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: gcs-service-account
  namespace: default
roleRef:
  kind: Role
  name: gcs-reader
  apiGroup: rbac.authorization.k8s.io
